db_config:
  host: "ip_address_of_your_timescale_server"
  port: "port_of_your_timescale_server"
  dbname: "postgres"
  user: "your_user_name"
  password: "your_password"

topics:
  /test: 
    msg_type: "std_msgs.msg.String"
    table_structure:
      - column_name: "data"
        column_type: "TEXT"

  /battery_level:
    msg_type: "std_msgs.msg.Float32"
    table_structure:
      - column_name: "data"
        column_type: "FLOAT"

  /temperature:
    msg_type: "std_msgs.msg.Float32"
    table_structure:
      - column_name: "data"
        column_type: "FLOAT"

  /imu:
    msg_type: "sensor_msgs.msg.Imu"
    table_structure:
      - column_name: "orientation_x"
        column_type: "FLOAT"
      - column_name: "orientation_y"
        column_type: "FLOAT"
      - column_name: "orientation_z"
        column_type: "FLOAT"
      - column_name: "orientation_w"
        column_type: "FLOAT"
      - column_name: "angular_velocity_x"
        column_type: "FLOAT"
      - column_name: "angular_velocity_y"
        column_type: "FLOAT"
      - column_name: "angular_velocity_z"
        column_type: "FLOAT"
      - column_name: "linear_acceleration_x"
        column_type: "FLOAT"
      - column_name: "linear_acceleration_y"
        column_type: "FLOAT"
      - column_name: "linear_acceleration_z"
        column_type: "FLOAT"
      - column_name: "orientation_covariance"
        column_type: "FLOAT[]"
      - column_name: "angular_velocity_covariance"
        column_type: "FLOAT[]"
      - column_name: "linear_acceleration_covariance"
        column_type: "FLOAT[]"

  # /odom:
  #   msg_type: "nav_msgs.msg.Odometry"
  #   table_structure:
  #     - column_name: "pose_pose_position_x"
  #       column_type: "FLOAT"
  #     - column_name: "pose_pose_position_y"
  #       column_type: "FLOAT"
  #     - column_name: "pose_pose_position_z"
  #       column_type: "FLOAT"
  #     - column_name: "pose_pose_orientation_x"
  #       column_type: "FLOAT"
  #     - column_name: "pose_pose_orientation_y"
  #       column_type: "FLOAT"
  #     - column_name: "pose_pose_orientation_z"
  #       column_type: "FLOAT"
  #     - column_name: "pose_pose_orientation_w"
  #       column_type: "FLOAT"
  #     - column_name: "twist_twist_linear_x"
  #       column_type: "FLOAT"
  #     - column_name: "twist_twist_linear_y"
  #       column_type: "FLOAT"
  #     - column_name: "twist_twist_linear_z"
  #       column_type: "FLOAT"
  #     - column_name: "twist_twist_angular_x"
  #       column_type: "FLOAT"
  #     - column_name: "twist_twist_angular_y"
  #       column_type: "FLOAT"
  #     - column_name: "twist_twist_angular_z"
  #       column_type: "FLOAT"
  #     - column_name: "pose_covariance"
  #       column_type: "FLOAT[]"
  #     - column_name: "twist_covariance"
  #       column_type: "FLOAT[]"

  # /cmd_vel:
  #   msg_type: "geometry_msgs.msg.Twist"
  #   table_structure:
  #     - column_name: "linear_x"
  #       column_type: "FLOAT"
  #     - column_name: "linear_y"
  #       column_type: "FLOAT"
  #     - column_name: "linear_z"
  #       column_type: "FLOAT"
  #     - column_name: "angular_x"
  #       column_type: "FLOAT"
  #     - column_name: "angular_y"
  #       column_type: "FLOAT"
  #     - column_name: "angular_z"
  #       column_type: "FLOAT"